"""empty message

Revision ID: db0b82776018
Revises: 536f1609caed
Create Date: 2021-05-04 19:23:37.951990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0b82776018'
down_revision = '536f1609caed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('taggg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'taggg')
    # ### end Alembic commands ###
